name: Upload GH Runner Count

on:
  schedule:
    # Every hour
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update-gh-runner-count:
    runs-on: ubuntu-latest
    environment: upload-gh-runner-count
    steps:
      - name: Checkout pytorch/test-infra
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up python 3.10
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.10'

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@50ac8dd1e1b10d09dac7b8727528b91bed831ac0 # v3.0.2
        with:
          role-to-assume: arn:aws:iam::308535385114:role/upload_to_ossci_raw_job_status
          aws-region: us-east-1

      - name: Install Dependencies
        run: python -m pip install boto3==1.19.12 requests==2.32.4

      - name: Update test times
        run: |
          python -m torchci.upload_gh_runner_count --github-token ${{ secrets.LIST_RUNNERS_GITHUB_TOKEN }} --upload
